#pragma once

//
// VoiceEcho 服务的设备参数
//
#define DEVICE_SET_VOICE_ECHO_MIC_SAMPLE_RATE    16000
#define DEVICE_SET_VOICE_ECHO_SPK_SAMPLE_RATE    16000
#define DEVICE_SET_VOICE_ECHO_SPK_VOLUME         70
#define DEVICE_SET_VOICE_ECHO_VAD_THRESHOLD      0.10f
#define DEVICE_SET_VOICE_ECHO_SILENCE_SEC        1
#define DEVICE_SET_VOICE_ECHO_MAX_RECORD_SEC     8
#define DEVICE_SET_VOICE_ECHO_PREROLL_MS         400
#define DEVICE_SET_VOICE_ECHO_VAD_DEBOUNCE       5
