#pragma once
#include <driver/gpio.h>

// ---- I2C 总线 ----
#define PIN_GPIO_I2C_SDA GPIO_NUM_41
#define PIN_GPIO_I2C_SCL GPIO_NUM_42

// ---- SPI2_HOST (HSPI) 引脚 —— 未用则为 GPIO_NUM_NC ----
#define PIN_GPIO_SPIH_MOSI GPIO_NUM_1
#define PIN_GPIO_SPIH_SCK  GPIO_NUM_2
#define PIN_GPIO_SPIH_MISO GPIO_NUM_NC

// ---- SPI3_HOST (FSPI) 引脚 —— 未用则为 GPIO_NUM_NC ----
#define PIN_GPIO_SPIF_SCK  GPIO_NUM_NC
#define PIN_GPIO_SPIF_MOSI GPIO_NUM_NC
#define PIN_GPIO_SPIF_MISO GPIO_NUM_NC

// ---- Lcd NV3007（4 线 SPI, 142x428）----
//   FPC pin 1  SDA     → SPI MOSI
//   FPC pin 2  SCL     → SPI SCK
//   FPC pin 3  RS      → DC  (命令/数据选择)
//   FPC pin 4  RESET   → RST (硬件复位)
//   FPC pin 5  CS      → CS  (片选)
//   FPC pin 6  FMARK/TE     (帧同步, 不接)
//   FPC pin 7  VDD          (3.3V)
//   FPC pin 8  LEDK         (背光负极 → GND)
//   FPC pin 9  LEDA         (背光正极 → 3.3V)
//   FPC pin 10 GND
#define PIN_GPIO_LCD_NV3007_RST GPIO_NUM_6   // FPC pin 4
#define PIN_GPIO_LCD_NV3007_CS  GPIO_NUM_5  // FPC pin 5
#define PIN_GPIO_LCD_NV3007_DC  GPIO_NUM_4   // FPC pin 3

// ---- Lcd NV3007 #2（待接线）----
#define PIN_GPIO_LCD_NV3007_2_CS  GPIO_NUM_NC
#define PIN_GPIO_LCD_NV3007_2_DC  GPIO_NUM_NC
#define PIN_GPIO_LCD_NV3007_2_RST GPIO_NUM_NC



// ---- Mic - INMP441 I2S MEMS（暂屏蔽）----
#define PIN_GPIO_MIC_INMP441_WS  GPIO_NUM_NC
#define PIN_GPIO_MIC_INMP441_SCK GPIO_NUM_NC
#define PIN_GPIO_MIC_INMP441_DIN GPIO_NUM_NC

// ---- Spk - MAX98357 I2S Amplifier（暂屏蔽）----
#define PIN_GPIO_SPK_MAX98357_DOUT GPIO_NUM_NC
#define PIN_GPIO_SPK_MAX98357_BCLK GPIO_NUM_NC
#define PIN_GPIO_SPK_MAX98357_LRCK GPIO_NUM_NC

// ---- Oled - SSD1306 0.91" I2C（暂屏蔽）----
#define PIN_GPIO_OLED_SSD1306_SDA GPIO_NUM_NC
#define PIN_GPIO_OLED_SSD1306_SCL GPIO_NUM_NC
#define PIN_GPIO_OLED_SSD1306_I2C_ADDR 0x3C

// ---- Built-in LED ----
#define PIN_GPIO_LED_BUILTIN GPIO_NUM_48

// ---- Driver TB6612 Motor RotateLayer（待接线）----
#define PIN_GPIO_DRIVER_TB6612_ROTATE_L1_PWM  GPIO_NUM_19   // PWMA
#define PIN_GPIO_DRIVER_TB6612_ROTATE_L1_IN1  GPIO_NUM_20   // AIN1
#define PIN_GPIO_DRIVER_TB6612_ROTATE_L1_IN2  GPIO_NUM_21   // AIN2
#define PIN_GPIO_DRIVER_TB6612_ROTATE_L2_PWM  GPIO_NUM_47
#define PIN_GPIO_DRIVER_TB6612_ROTATE_L2_IN1  GPIO_NUM_48
#define PIN_GPIO_DRIVER_TB6612_ROTATE_L2_IN2  GPIO_NUM_N45
#define PIN_GPIO_DRIVER_TB6612_ROTATE_STBY    GPIO_NUM_7   // STBY

// ---- Driver TB6612 Motor Wheels ----
//   VCC+VM → 3.3V; AO1/AO2 → N20 M1/M2
#define PIN_GPIO_DRIVER_TB6612_WHEEL_W1_PWM  GPIO_NUM_NC   // PWMA
#define PIN_GPIO_DRIVER_TB6612_WHEEL_W1_IN1  GPIO_NUM_NC   // AIN1
#define PIN_GPIO_DRIVER_TB6612_WHEEL_W1_IN2  GPIO_NUM_NC   // AIN2
#define PIN_GPIO_DRIVER_TB6612_WHEEL_W2_PWM  GPIO_NUM_NC  // PWMB
#define PIN_GPIO_DRIVER_TB6612_WHEEL_W2_IN1  GPIO_NUM_NC  // BIN1
#define PIN_GPIO_DRIVER_TB6612_WHEEL_W2_IN2  GPIO_NUM_NC  // BIN2
#define PIN_GPIO_DRIVER_TB6612_WHEEL_STBY    GPIO_NUM_NC   // STBY

// ---- Motor N20 RotateLayer1 Encoder（待接线）----
#define PIN_GPIO_MOTOR_N20_ROTATE_L1_ENC_A GPIO_NUM_13
#define PIN_GPIO_MOTOR_N20_ROTATE_L1_ENC_B GPIO_NUM_14

// ---- Motor N20 RotateLayer2 Encoder（待接线）----
#define PIN_GPIO_MOTOR_N20_ROTATE_L2_ENC_A GPIO_NUM_NC
#define PIN_GPIO_MOTOR_N20_ROTATE_L2_ENC_B GPIO_NUM_NC

// ---- Motor N20 Wheel1 Encoder ----
//   C1=GPIO15  C2=GPIO16
#define PIN_GPIO_MOTOR_N20_WHEEL_1_ENC_A GPIO_NUM_NC
#define PIN_GPIO_MOTOR_N20_WHEEL_1_ENC_B GPIO_NUM_NC

// ---- Motor N20 Wheel2 Encoder（待接线）----
#define PIN_GPIO_MOTOR_N20_WHEEL_2_ENC_A GPIO_NUM_NC
#define PIN_GPIO_MOTOR_N20_WHEEL_2_ENC_B GPIO_NUM_NC
